### ISSUE TITLE
Any reason why we can't combine forces

### ISSUE THREAD

**Issue by posix4e** [dirk/metrics_distributor#1]
I'm the guy behind rust-metrics. Curious if you want to join forces?

**Comment by posix4e** [comment]
https://github.com/posix4e/rust-metrics

**Comment by posix4e** [comment]
I'd like to pull your collectors into rust-metrics. That way you can use the super efficient embedded method or metrics_distributor. Working together we can effectively double each others users base.

**Comment by dirk** [comment]
Hi @posix4e, and thanks for reaching out! Let me read through `rust-metrics` and get back to you. 😄

(At first glance I'm not sure our goals overlap enough for merging, but at the very least I think we may be able to cross-polinate to help each other out.)
